### ISSUE TITLE
Errors during generation, not sure what's wrong

### ISSUE THREAD

**Issue by mvestergaard** [KirillOsenkov/SourceBrowser#102]
I'm getting errors on all projects during generation of the site, which in the end contains the projects, but no code.

In the first phase of the generation, each project outputs something similar to this:
```
10:39:25 21-11-2018 10:39:25: First chance exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.Finalize()
10:39:25 Workspace failed: Msbuild failed when processing the file 'C:\Source\Roadmap\merge2\Apps\Broker\BrokerEndPointService\Nis.Broker.CorePlugin\Nis.Broker.CorePlugin.csproj' with message: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
10:39:25 Msbuild failed when processing the file 'C:\Source\Roadmap\merge2\Apps\Broker\BrokerEndPointService\Nis.Broker.CorePlugin\Nis.Broker.CorePlugin.csproj' with message: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
```
In the final phase of the generation, each projects outputs this error:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0, Object arg1)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.GenerateProjectFile()
```

It looks like it stems from pretty much the same thing. Any ideas what might be wrong?

**Comment by mvestergaard** [comment]
Given this: https://developercommunity.visualstudio.com/content/problem/311632/error-after-updating-to-1580-invalid-static-method.html

It could be incompatibility with some of the latest updates to visual studio/msbuild?

**Comment by mvestergaard** [comment]
I'm using the nuget version btw. Could it be because it hasn't been updated in a while? I'm thinking it's due to #91 

I'll try running from source. However the plan is to have this running in a CI environment, so the nuget package would be a lot easier to deal with.

**Comment by mvestergaard** [comment]
Running from source yield much better results. I still get a lot of these errors however, i'm not sure whether they are harmful or not.

```
11:17:33 Project generation failed for: Web\Nis.Portal\Nis.Portal.Shell\Nis.Portal.Shell.csproj
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataOnlyImageReferenceAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Document.<GetSemanticModelAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SourceBrowser.HtmlGenerator.DocumentGenerator.<Generate>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.<>c__DisplayClass58_0.<<Generate>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SourceBrowser.HtmlGenerator.ProjectGenerator.<Generate>d__58.MoveNext()
```

**Comment by KirillOsenkov** [comment]
Yes, unfortunately the NuGet package is very old, sorry about that.

Running from source is best. Haven't seen the last one before (the Roslyn one). Do you have a small stand-alone project that I could try this on?

**Comment by mvestergaard** [comment]
I'll try to narrow down the cause later when I have the time. I'll open a separate issue for that if I find something. It's unfortunately closed source internal stuff that I can't share.

In regards to the nuget package. Any chance of having an updated one published?

**Comment by KirillOsenkov** [comment]
Can you try https://www.nuget.org/packages/SourceBrowser/1.0.19 and see if it works? I've just updated it.

**Comment by mvestergaard** [comment]
That seems to just crash silently. No stack trace given, just a "HtmlGenerator has stopped working" dialog.

**Comment by mvestergaard** [comment]
I think we're battling a bit of a time difference. I'll try to squeeze it in at work tomorrow. I'll probably try to debug the other exceptions I wrote about above too while I'm at it.

**Comment by mvestergaard** [comment]
Alright, it appears the crash happens during: `AssemblyNameExtractor` line 74. Internally an exception occurs
`System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)`
In `FirstChanceExceptionHandler` line 128 it attempts to use the stacktrace from the exception, but the stacktrace is `null`.

Here's a screenshot
![image](https://user-images.githubusercontent.com/2027834/48934594-f985c000-ef04-11e8-957b-5931e74f5c63.png)

We do have some COM references in one or two projects, could that be the cause?

**Comment by mvestergaard** [comment]
The `An item with the same key has already been added.` exception is a lot more difficult to track down the cause of.
The exception is thrown here https://github.com/KirillOsenkov/SourceBrowser/blob/master/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs#L47

But given the stack trace, my best guess of the actual source is here https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs#L638

Async seems to make it very difficult to break on the actual exception and identify why it happens.

**Comment by mvestergaard** [comment]
I've opened pull request #103 to handle the stack trace being null

**Comment by KirillOsenkov** [comment]
Thanks for the PR, I merged.

I also noticed I'm missing a catch {} block in AssemblyNameExtractor.cs - if it fails getting the assembly name just default to the project name. I've just pushed that change too.

Would be nice to get the callstack for the COMException, it's weird.

Regarding the Roslyn exception, it looks like one of your projects may contain a duplicate project or assembly reference. I'm going to try to reproduce.

**Comment by KirillOsenkov** [comment]
Yup, I was able to reproduce the Roslyn issue. Your .csproj likely has a duplicate `ProjectReference` to the same project.

**Comment by mvestergaard** [comment]
Okay, yea, I was kinda suspecting that too. It's a big solution with more than 300 projects, so those kind of things are difficult to find, I'll probably write a little tool to help find it.

**Comment by KirillOsenkov** [comment]
When you see the exception, you can easily get the project being currently analyzed, and that's the project with duplicate references. Just eyeball the .csproj and you'll find it.

**Comment by mvestergaard** [comment]
That doesn't really seem to be the case. Does it only look at the project itself, or the referenced projects as well?
Because the project from the error message I pasted further up, does not have duplicate project references.

**Comment by KirillOsenkov** [comment]
Good news - I've just pushed a fix to deduplicate project references so you don't have to worry about it: 
https://github.com/KirillOsenkov/SourceBrowser/commit/00cacc6f5abe78e72ce7ba8ed8fc7bdc86eb2273

I still recommend that you find and remove duplicate project references, but it should no longer block you.

**Comment by mvestergaard** [comment]
Great. That appears to have done the trick.

I still have a few errors related to projects that use COM. Also projects converted to the new .csproj format that use Workflows/Xaml produce errors, but I don't think that relates to this tool, it's more of an msbuild thing in general (it produces warnings in the build too)

I'll try to track down where those duplicate project references are, because it's not really obvious.

Btw, is there any way to make the tool only log warnings and errors? They kind drown in the spam atm.

**Comment by KirillOsenkov** [comment]
And I just added a log warning for each duplicate project reference so next time you run it it'll tell you where the duplicates are.https://github.com/KirillOsenkov/SourceBrowser/commit/235c5afdb98f3c02156c303121278989ef9bc5db

**Comment by KirillOsenkov** [comment]
Regarding the log verbosity - I don't think I can tweak it at the moment, but you can go through calls to Log and comment out the ones you don't need. Longer term I should come up with configurable verbosity. Most egregious errors are logged into a separate log called Errors.txt.

**Comment by KirillOsenkov** [comment]
For COM, if you create a simple project that reproduces the error I can help investigate. Same for Workflow/Xaml. 

See if using http://msbuildlog.com can help with investigating those.

**Comment by mvestergaard** [comment]
I'll try to come up with something useful to find those issues.
Here are the errors output by HtmlGenerator, if it at all helps:
```
21:06:50 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows\Nis.Workflows.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:50 Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows\Nis.Workflows.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:55 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Customers\GI\Libraries\GIWorkFlow\GIWorkFlow\GIWorkFlow.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:55 Msbuild failed when processing the file 'C:\source\roadmap\Customers\GI\Libraries\GIWorkFlow\GIWorkFlow\GIWorkFlow.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:55 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Customers\Gouda\Libs\Nis.Customers.Gouda.Workflows\Nis.Customers.Gouda.Workflows.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:55 Msbuild failed when processing the file 'C:\source\roadmap\Customers\Gouda\Libs\Nis.Customers.Gouda.Workflows\Nis.Customers.Gouda.Workflows.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:56 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Customers\SCTI\Libraries\Nis.Customers.SCTI.Converga\Nis.Customers.SCTI.Converga.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:56 Msbuild failed when processing the file 'C:\source\roadmap\Customers\SCTI\Libraries\Nis.Customers.SCTI.Converga\Nis.Customers.SCTI.Converga.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:57 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Customers\WTP\Libraries\Nis.Customers.WTP\Nis.Customers.WTP.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:57 Msbuild failed when processing the file 'C:\source\roadmap\Customers\WTP\Libraries\Nis.Customers.WTP\Nis.Customers.WTP.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:06:58 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\GoTrex\GoTrex.NET.vbproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2725, 5): The "ResolveComReference" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
21:06:58 Msbuild failed when processing the file 'C:\source\roadmap\GoTrex\GoTrex.NET.vbproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2725, 5): The "ResolveComReference" task could not be instantiated from "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
21:06:58 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\GoTrex\GoTrex.NET.vbproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2725, 5): The "ResolveComReference" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
21:06:58 Msbuild failed when processing the file 'C:\source\roadmap\GoTrex\GoTrex.NET.vbproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2725, 5): The "ResolveComReference" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
21:07:00 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows.BulkProcessing.Tests\Nis.Workflows.BulkProcessing.Tests.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:07:00 Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows.BulkProcessing.Tests\Nis.Workflows.BulkProcessing.Tests.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:07:00 Workspace failed: Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows.Tests\Nis.Workflows.Tests.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
21:07:00 Msbuild failed when processing the file 'C:\source\roadmap\Libs\Nis.Workflows.Tests\Nis.Workflows.Tests.csproj' with message: C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Xaml.targets: (106, 5): XC1020: Build error occurred in the XAML MSBuild task: 'Could not load file or assembly 'XamlBuildTask, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'
```

**Comment by mvestergaard** [comment]
I managed to track down the duplicate project references with the help of the warnings. Thanks, that was very helpful.

**Comment by mvestergaard** [comment]
This simple workflow projects appears to reproduce the Xaml issue
[WorkflowConsoleApplication1.zip](https://github.com/KirillOsenkov/SourceBrowser/files/2611685/WorkflowConsoleApplication1.zip)

**Comment by mvestergaard** [comment]
Here's a reproduction of the COM issue
[WindowsFormsApp1.zip](https://github.com/KirillOsenkov/SourceBrowser/files/2611696/WindowsFormsApp1.zip)

**Comment by KirillOsenkov** [comment]
OK good news, I've pushed a fix for the COM reference issue. Turns out ResolveCOMReference is creating appdomains, and I use a special tool called MSBuildLocator to subscribe to the AssemblyResolve event of an appdomain to specify which MSBuild binaries to load. It wasn't finding MSBuild binaries when starting other appdomains.

Here's the fix: https://github.com/KirillOsenkov/SourceBrowser/commit/962457bdc0f778461f85ccff8438f9f2cc0a72b8

**Comment by KirillOsenkov** [comment]
And the WorkflowConsoleApp build failure is an actual bug in MSBuild:
https://github.com/Microsoft/msbuild/issues/3956

**Comment by KirillOsenkov** [comment]
OK turns out it's not necessarily a bug. To properly build Workflow projects you need to install the Workflow component in the Visual Studio Installer:
![image](https://user-images.githubusercontent.com/679326/48965426-ad249980-ef71-11e8-85de-66daca86ff97.png)

It's under Development Activities.

After you install, the workflow projects should build fine.

Let me know if all your issues are now resolved. I can then build and publish an updated NuGet package with all the fixes.

**Comment by KirillOsenkov** [comment]
I've optimistically published https://www.nuget.org/packages/SourceBrowser/1.0.20 with all the latest fixes.

**Comment by mvestergaard** [comment]
Windows Workflow Foundation is installed already, otherwise I don't think I'd have the project templates in visual studio. They also build just fine through VS.

But thanks for the new version, I'll see monday whether the result it produces looks better than the last attempt.

**Comment by mvestergaard** [comment]
Output from 1.0.20 looks great, despite the few remaining error messages.

Btw, are you aware that you published it to nuget as `SourceBrowser` and not `Microsoft.SourceBrowser` like the previous versions?

**Comment by KirillOsenkov** [comment]
Great to hear!

The NuGet rename is intentional, they made it too hard to publish under "Microsoft." prefix, I don't want to go through that much friction (signing etc).

I'll close this issue but feel free to open new issues for the remaining errors if you like.
