### ISSUE TITLE
No results found for Enumerable.cs

### ISSUE THREAD

**Issue by IrisClasson** [KirillOsenkov/SourceBrowser#140]
Listed as an example on the main page at [source.dot.net](https://source.dot.net/), but yields no results when the link is clicked and the search is done. Tried with other classes such as List, but the result seems to be incomplete or missing.

Not sure if the problem is the compiled hosted version at [https://source.dot.net/](https://source.dot.net/ )  or a bug in the project.

**Comment by JesperTreetop** [comment]
I've seen this with many items for a few days, like TimeSpan today. There's no way to contact whoever keeps source.dot.net alive, so like @IrisClasson I'm chiming in here. This project is more or less not being worked on any longer, but it looks like there was a change recently to which source files to include which may have affected that site (or they stopped including all the files in the build). It doesn't affect the sourceof.net .NET Framework site, but I imagine it's not being constantly rebuilt the way the .NET Core site is.

**Comment by KirillOsenkov** [comment]
The team is actively investigating. The fix is non-trivial and related to indexing a mix of .NET Core 3.1 and .NET 5 codebases. Watch this issue for updates and thanks for your patience.

**Comment by KirillOsenkov** [comment]
This is now fixed!

**Comment by JesperTreetop** [comment]
WPF still appears to be missing. FrameworkElement and DispatcherTimer exist on sourceof.net (.NET Framework) but not on source.dot.net.

**Comment by KirillOsenkov** [comment]
@alexperovich FYI

**Comment by alexperovich** [comment]
Looking, it looks like the binlogs from WPF are even more strange

**Comment by KirillOsenkov** [comment]
ping me if I can help with anything

**Comment by alexperovich** [comment]
It also doesn't even look like PresentationFramework.dll was built.... This is very strange

**Comment by KirillOsenkov** [comment]
I think PresentationFramework is a multimodule assembly, its part is written in managed C++. Maybe there’s weirdness around that build?

**Comment by alexperovich** [comment]
Yea, the binlog doesn't have any compilation for PresentationFramework. I can keep looking, but I don't know how it is actually built.

**Comment by alexperovich** [comment]
Aha, it failed because the native library it depends on didn't build successfully. There is some missing library. I don't know how to fix this.

**Comment by KirillOsenkov** [comment]
Hey @vatsan-madhavan @rladuca @stevenbrix whenever one of you has a chance next week could you please help @alexperovich fix a build failure in WPF build? Alex maintains https://source.dot.net which includes the WPF source code. It's a nice useful site for the community and it would be great to have up-to-date WPF code indexed there.

Alex, could you please write up an email or a page about how the CI build works for the website indexer, and where the relevant source is. Please include me and the folks above ^^ Ideally we should have a binlog too.

Thanks!

**Comment by vatsan-madhavan** [comment]
There was a question recently about how to build a GitHub Action to build dotnet/wpf (in a fork). We tried to help and the OP was eventually able to build it successfully. Here it is - https://github.com/dotnet/wpf/issues/2290. 

Please read through it and maybe it will help you figure out what it's going to take to build WPF sources in a different environment. 

A few other thoughts - 

- There is probably no avoiding building the whole thing - assuming the repo has to be built at all to index sources. That means building C++/CLI and C++ sources. 
  - There might be a way to avoid building C++ sources, but building C++/CLI would be unavoidable. 
   - The repo usually has 2 (sometimes 3) projects that build binaries with the same name. For e.g.,..
     - [PresentationUI.csproj](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationUI/PresentationUI.csproj) - main
      - [PresentationUI-ref.csproj](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationUI/ref/PresentationUI-ref.csproj) - ref assembly
      - [PresentationUI-PresenationFramework-impl-cycle.csproj](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/cycle-breakers/PresentationUI/PresentationUI-PresentationFramework-impl-cycle.csproj) - a [_cycle breaker_](https://github.com/dotnet/wpf/blob/master/Documentation/cycle-breakers.md) assembly
   - You'll need some precedence rules to figure which one matters more etc.  
- A logical implication of C++ involvement is that `dotnet` builds won't do - it will have to be `msbuild` build. 
- MSBuild in turn implies that the build/CI pipeline will require Visual Studio. 
  - [global.json](https://github.com/dotnet/wpf/blob/master/global.json) indicates the version needed (16.5 or newer)
  - [wpf.vsconfig](https://github.com/dotnet/wpf/blob/master/Documentation/wpf.vsconfig) outlines the workloads needed.

**Comment by alexperovich** [comment]
I added code to skip the cycle-breaker and ref projects and it looks to be working now. The build agents can build the while project successfully. My local machine doesn't have the right C++ build stuff.

**Comment by vatsan-madhavan** [comment]
@alexperovich In case you weren't aware, you can import [wpf.vsconfig](https://github.com/dotnet/wpf/blob/master/Documentation/wpf.vsconfig) using instructions from [Import or export installation configurations](https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019). This should allow you to build the dotnet/wpf repo locally. Probably not a concern anymore, but good info to have for future.

**Comment by jasonkuo41** [comment]
Now System.Private.CoreLib is nowhere to be found too.

**Comment by alexperovich** [comment]
I fixed the wpf build part a while ago. dotnet/runtime is now not building... again. I'm tracking that with https://github.com/dotnet/source-indexer/issues/53.
